test/py/requirements.txt: increase filelock version
building on gitlab with

image: ${MIRROR_DOCKER}/trini/u-boot-gitlab-ci-runner:jammy-20240911.1-08Dec2024

drops error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
virtualenv 20.13.0+ds requires filelock<4,>=3.2, but you have filelock 3.0.12 which is incompatible.

Increase to version 3.2.0

Signed-off-by: Heiko Schocher <hs@nabladev.com>