lib: import sm3 256 hash parts from linux
Implement SM3_256 Hash algorithm, based on
linux commit f83a4f2a4d8c: ("Merge tag 'erofs-for-6.17-rc6-fixes' of git://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs")

Therefore add the needed parts from linux.

Signed-off-by: Heiko Schocher <hs@nabladev.com>
Commit-notes:
This patch drops a lot of checkpatch warnings, ignored them
as tried to stay as close as possible with linux code.
END
Series-changes: 2
add sm3_hash to header file, so we can use it.
Series-changes: 3
add comments from Ilias
- use sizeof(*sctx) instead of sizeof(struct sm3_context)
- use output[] instead of output[SM3_DIGEST_SIZE] comment from Ilias
  This leaded to CI error:
  +lib/sm3.c:241:50: error: argument 2 of type ‘uint8_t[]’ {aka ‘unsigned char[]’} with mismatched bound [-Werror=array-parameter=]
  +  241 | void sm3_final(struct sm3_context *sctx, uint8_t output[])
  +      |                                          ~~~~~~~~^~~~~~~~
  see:
  https://dev.azure.com/hs0298/hs/_build/results?buildId=192&view=logs&j=182673a4-17b9-5c0c-69ad-98f742450579&t=34b689f8-3e29-5ffe-50ea-32bfe99f47c7&l=334
  so made this change back to v2 state of the series
- seperate linux and U-Boot parts into 2 commits

Signed-off-by: Heiko Schocher <hs@nabladev.com>