test/py/requirements.txt: remove unittest2 and testtools
unittest2 and testtools leads in:

Collecting argparse (from unittest2>=1.0.0->testtools==2.3.0->-r /builds/u-boot/custodians/u-boot-i2c/tbottesting/../test/py/requirements.txt (line 26))
  Downloading argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)

which breaks pytest 6.2.5 with

  File "/home/uboot/.local/lib/python3.10/site-packages/_pytest/config/argparsing.py", line 381, in __init__
    argparse.ArgumentParser.__init__(
TypeError: ArgumentParser.__init__() got an unexpected keyword argument 'allow_abbrev'

Signed-off-by: Heiko Schocher <hs@nabladev.com>