led: add function naming option from linux
in linux we have the option to create the name of a led
optionally through the following properties:

- function
- color
- function-enumerator

This patch adds support for parsing this properties if there
is no label property.

To be as close as possible to linux import the following files
from it:

include/dt-bindings/leds/common.h
include/linux/uapi/linux/uleds.h

base commit was:
commit: b8f52214c61a ("Merge tag 'audit-pr-20241205' of git://git.kernel.org/pub/scm/linux/kernel/git/pcmoore/audit")

The led name is created in led_post_bind() and we need some
storage place for it. Currently this patch prevents to use
malloc() instead it stores the name in new member :

        char name[LED_MAX_NAME_SIZE];

of struct led_uc_plat. While at it append led tests for the
new feature.

Signed-off-by: Heiko Schocher <hs@denx.de>
Series-version: 1
Series-to: uboot

Commit-notes:
as we introduce a new element in struct led_uc_priv, may we should add
this functionality through a new Kconfig option? (Which also would make
this optional and save some bytes for boards who do not need this...)

Ignored a lot of checkpatch warnigs for file include/dt-bindings/leds/common.h

WARNING: Block comments use * on subsequent lines
+/*   Obsolete equivalents: "tpacpi::thinklight" (IBM/Lenovo Thinkpads),
+     "lp5523:kb{1,2,3,4,5,6}" (Nokia N900) */
WARNING: Block comments use a trailing */ on a separate line
+     "lp5523:kb{1,2,3,4,5,6}" (Nokia N900) */
WARNING: Block comments use * on subsequent lines
+/* System LEDs, usually found on system body.
+   platform::mute (etc) is sometimes seen, :mute would be better */
WARNING: Block comments use a trailing */ on a separate line
+   platform::mute (etc) is sometimes seen, :mute would be better */
WARNING: Block comments use * on subsequent lines
+/*   Used RGB notification LEDs common on phones.
+     Obsolete equivalents: "status-led:{red,green,blue}" (Motorola Droid 4),
WARNING: Block comments use a trailing */ on a separate line
+     "lp5523:{r,g,b}" (Nokia N900) */

as it is copied from linux

commit: b8f52214c61a ("Merge tag 'audit-pr-20241205' of git://git.kernel.org/pub/scm/linux/kernel/git/pcmoore/audit")

Azure build:
https://dev.azure.com/hs0298/hs/_build/results?buildId=146&view=results
fails with:
"""
https://dev.azure.com/hs0298/hs/_build/results?buildId=146&view=logs&j=2f11968a-a55a-5abb-f256-768f7ca79083&t=6eebae2f-48d7-5c84-e205-7fdf39a976c7
_____________________ test_ut[ut_dm_dm_test_cmd_hash_md5] ______________________
test/py/tests/test_ut.py:610: in test_ut
    assert output.endswith('Failures: 0')
E   assert False
E    +  where False = <built-in method endswith of str object at 0x55e238c08c60>('Failures: 0')
E    +    where <built-in method endswith of str object at 0x55e238c08c60> = 'Test: dm_test_cmd_hash_md5: hash.c\r\r\nhash - compute hash message digest\r\r\n\r\r\nUsage:\r\r\nhash algorithm addr...md5 $loadaddr 0", 0): Expected 0x0 (0), got 0x1 (1)\r\r\nTest \'dm_test_cmd_hash_md5\' failed 1 times\r\r\nFailures: 1'.endswith
----------------------------- Captured stdout call -----------------------------
=> ut dm dm_test_cmd_hash_md5

Test: dm_test_cmd_hash_md5: hash.c

hash - compute hash message digest
"""

I do not see, that this is introduced through my patch.
(correct me, if I am wrong!)

running this command on my build machine in started sandbox:
"""
=> ut dm dm_test_cmd_hash_md5
Test: dm_test_cmd_hash_md5: hash.c
Failures: 0
=>
"""

works fine.

END